exports seemed to introduce dynamic import errors
Without this change this, when doing `import {CloudbeesProvider} from 'cloudbees-openfeature-provider-node'` I was getting the error
```
Error: Dynamic require of "http" is not supported
```
🤷‍